name: Generate Weekly Journal Summaries

on:
  schedule:
    # Runs at 3:00 AM UTC every Sunday
    - cron: '0 3 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r summary/requirements.txt

      - name: Run the summary script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # You would store your service account JSON as a multi-line secret
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
        run: |
          # Write the secret to a temporary file
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > ./service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json
          python summary/main.py
